fix(tests): history is not defined
⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯
ReferenceError: history is not defined
 ❯ finalizeNavigation node_modules/.pnpm/vue-router@5.0.4_@vue+compiler-sfc@3.5.32_vue@3.5.32_typescript@5.9.3_/node_modules/vue-router/dist/vue-router.js:1386:35
 ❯ node_modules/.pnpm/vue-router@5.0.4_@vue+compiler-sfc@3.5.32_vue@3.5.32_typescript@5.9.3_/node_modules/vue-router/dist/vue-router.js:1317:21

This error originated in "tests/unit/pages/chats-new.spec.ts" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 Test Files  39 passed (39)
      Tests  274 passed (274)
     Errors  1 error
   Start at  15:39:37
   Duration  8.19s (transform 3.59s, setup 2.63s, import 4.37s, tests 7.82s, environment 5.99s)

 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.